let name="Vijay Shankar Patel";
let school="Masai school";
let grade="A";
let section="Web-23";
let rollno="fw-0904";
let JS101=90;
let DSA101=81;
let CC101=79;
let total=300;
let marks_scored=JS101+DSA101+CC101;
console.log(marks_scored);
console.log("--------------------------------------");
console.log("|","Name         :",name,  "|");
console.log("|","School       :",school,"       |");
console.log("|","Grade        :",grade,"                  |");
console.log("|","Section      :",section,"             |");
console.log("|","Roll No      :",rollno,"            |");
console.log("|","JS101        :",JS101,"                 |");
console.log("|","DSA101       :",DSA101,"                 |");
console.log("|","CC101        :",CC101,"                 |");
console.log("|","Marks Scored :",marks_scored,"/",total,"          |");
console.log("--------------------------------------");